### ISSUE TITLE
Support for monochromatic dpx files?

### ISSUE THREAD

**Issue by mikmake** [usc-imi/aeo-light#12]
One more question, is there a way to extract audio from monochromatic dpx files?

**Comment by sjohnson-imi** [comment]
AEO-Light 2 is built to read both 3-channel and 1-channel DPX files, yeah. The process is the same for either. Does it fail to open your single channel DPX files? If so, can you provide a few samples?

**Comment by mikmake** [comment]
Ok, good to hear. 
When opening 1-channel dpx sequence I got three small images of the frame instead of one, positioned parallel in the upper third of the window.
Of course I can provide a few samples. What´s your e-mail adress? I will send you a link tomorrow.
Thanks a lot!

**Comment by sjohnson-imi** [comment]
Yeah -- that definitely seems like the DPX files are being interpreted as 3-channel. My email is sjohnson.imi@gmail.com

**Comment by sjohnson-imi** [comment]
Resolved in version 2.3.2
