### ISSUE TITLE
Sound Timecode advance not working 2.3.2

### ISSUE THREAD

**Issue by ziggyphenocious** [usc-imi/aeo-light#15]
If I render with Sound Timecode Advance enabled, it works the same as if it were disabled. There is no advance. I have to manually move soundtrack 20 frames for picture to be in sync.  I am using daVinici Resolve to sync audio. I get same result with other syncing programs.

**Comment by wilsbacher** [comment]
Confirming that we're looking into this.  More soon.

**Comment by ziggyphenocious** [comment]
We have tried this a few times, and it does not always happen.

**Comment by sjohnson-imi** [comment]
I found a bug in the WAV file header's size entry that me be causing the issue. Can I send you an updated executable to test? (Email me at sjohnson.imi@gmail.com)
