### ISSUE TITLE
Neg Density track clipping

### ISSUE THREAD

**Issue by ziggyphenocious** [usc-imi/aeo-light#16]
We have been scanning a lot of negative variable density and have noticed in the various audio recovery applications that there is often some "squaring" of the tops of the waveform.  I have attached images showing the settings and the appearance of the waveform.  Is there any different settings we should try to improve this?  The sound is much better than with our red led Sondor reader, but there is still some distortion we have not been successful in eliminating.  

![nr002527-s_aeo_snip1](https://user-images.githubusercontent.com/13665425/51219635-9140d280-18e6-11e9-924c-7f7beac1e7ea.png)
![nr002527-s_aeo_snip2](https://user-images.githubusercontent.com/13665425/51219636-9140d280-18e6-11e9-98a3-2a33dfdce31f.png)
![nr002527-s_aeo_snip3](https://user-images.githubusercontent.com/13665425/51219637-9140d280-18e6-11e9-95c2-6263cdadd519.png)

**Comment by sjohnson-imi** [comment]
Just judging by the picture, it seems the squaring is accurately reproducing that part of the scan (the gray stripes in the soundtrack area) -- that the waveform was either clipped in the original recording or perhaps in the scanning process. But if you'd like to make a few raw frames available in dropbox or Google drive for us, we can take a shot at tweaking those settings to draw out additional detail. (You can send a link to me at sjohnson.imi@gmail.com)
