### ISSUE TITLE
I see that a newer version of FFmeg now has cineform support

### ISSUE THREAD

**Issue by expertpcb150** [usc-imi/aeo-light#17]
I 'd like to update using the latest FFmeg binaries for Mac OSX so that I could load Cineform file directly into AEO. I have done some Xcode programing builds.  Not sure what I would have to do here but am willing to try with some support and guidance... or do you have  and Archived directory that can be downloaded and then I just launch the project and update where necessary. 
I am not a total novice but have only worked in Xcode on a Mac.
George

**Comment by retokromer** [comment]
As long as I know, the situation is still the same as a little more than three years ago, when CineForm was implemented into FFmpeg. There is a decoder for many flavours, but not the Bayer-based RAW, which would really be of interest for AEO-Light:

    12/16-bit CFA Bayer RAW, log encoded and compressed at 12-bit progressive

**Comment by expertpcb150** [comment]
Thanks for responding... I saw this
https://fxhome.com/forum/discussion/45239/cineform-now-fully-open-source
which seemed to imply that it would be possible to finally incorporate Full Cineform support in AEO. As you probably know going through the painful conversion of CineForm to a usuable format taht can be read by AEO is very time consuming.

**Comment by retokromer** [comment]
Yes, the SDK has been released here on [GutHub](https://github.com/gopro/cineform-sdk) on 2017-10-15. On my end, I have tried to use it, but it was finally much simpler to hack it for our needs. Yet, sadly, I didn’t had the time and energy so far to make a clean PR for implementing the Bayer-based format we use into FFmpeg.

**Comment by expertpcb150** [comment]
Unfortunately for me I have to do something... I have numerous 5K scans in Cineform format which require first converting them using Premiere to export in a custom 5K DV file (30 minute feature takes 5days approximately... and then sucking it into AEO and then extracting the audio (using 48k sampling) then takes another 3Days Approximately....  All of this to get decent sound quality on the music portion of the audio. There has to be a better way and I need to try to solve this.

BTW thanks for responding...

**Comment by retokromer** [comment]
>30 minute feature takes 5days approximately

That’s very strange indeed! It should be possible to export 5K CineForm to DPX by Resolve between real time and its double.

**Comment by expertpcb150** [comment]
OK
I thought I had to be doing something wrong.... So I use Premiere and export as DPX? and NOT as DV correct? 
So I 'll have to look at how to do that.
If that will cut the time down to just a few hours I can live with that.
The AEO at high res takes a long while as well... any suggestions on how to speed that up?

Thanks

**Comment by retokromer** [comment]
>So I use Premiere and export as DPX? and NOT as DV correct?

DPX or TIFF have a higher image quality, therefore a better sound quality can be extracted from them.

>The AEO at high res takes a long while as well... any suggestions on how to speed that up?

I’ll try to check that tomorrow. (Then I’ll be out of office until Friday.) What computer model, how much RAM and what OS version do you use?

**Comment by expertpcb150** [comment]
The original scan in CineForm is 4874 by 3232
I have exported at custom DV maintaining same resolution and progressive.
I'm on MacOSX 10.13.6 with 8 Gig ram.  1 Terabyte internal and 5 Terabytes external
MacPro Laptop 2.8 GHz Intel Core i7

Once I have the audio extracted and EQed ,then its added back to video and exported in cropped format with window bars as needed and centered accordingly..

**Comment by retokromer** [comment]
>The original scan in CineForm is 4874 by 3232

4864 x 3232? Kinetta?

>I'm on MacOSX 10.13.6 with 8 Gig ram.

I’ll try to test on a similar setting. 8 GB RAM is possibly the weak point, also because macOS 10.13 itself uses a lot of it.

**Comment by expertpcb150** [comment]
Yes the scans were done on a Kinetta..

I haven't seen any recommendations as to what memory was needed... However not sure if that would make that much of a difference.

**Comment by expertpcb150** [comment]
What would you advise? as to hardware and memory? See if I can get that funded for  a future acquisition

**Comment by retokromer** [comment]
Sorry, I could not run a test today. I’ll be at the lab again only on Friday.

**Comment by expertpcb150** [comment]
OK Thx

**Comment by wilsbacher** [comment]
AEO crunches the audio using OpenGL, so the capabilities of the graphics card provide the limiting factor for processing speed. Your kinetta software also relies heavily on the graphics card--and Jeff usually includes a pretty robust card. Try running AEO on the kinetta PC as a point of comparison--and DPX will be processed faster than an equivalent video source.

**Comment by expertpcb150** [comment]
OK Thx

**Comment by expertpcb150** [comment]
hi
wondering if your tests led to some revised advice?

thx

**Comment by wilsbacher** [comment]
Closing this thread as it was initially about FFMpeg and Cineform. You can repost as a new thread relating to hardware configurations.

**Comment by retokromer** [comment]
FYI @expertpcb150 : This morning I could run tests on iMac (27-inch, late 2013) and I got from 16-bit DPX at Kinetta resolution a sound extraction  speed of 4.21 fps in average.
