### ISSUE TITLE
[wish] user’s manual

### ISSUE THREAD

**Issue by retokromer** [usc-imi/aeo-light#18]
In my opinion, it would be beneficial for this project to update the user’s manual. The source could be published here on GitHub as well. This would allow more easily to contribute.

I also suggest to add the `Makefile` here on GitHub.

And a `README.md` file.

**Comment by expertpcb150** [comment]
A sample test file and with conversion times would help new users determine if they have set the software and hardware up correctly...

Would like to help...

**Comment by wilsbacher** [comment]
We ran performance tests like these during development. I should be able to package up some public domain scans (as DPX and ProRes 422) this week.

**Comment by retokromer** [comment]
visibly no interest, closing
