### ISSUE TITLE
Linux compile

### ISSUE THREAD

**Issue by edouardchalaron** [usc-imi/aeo-light#2]
Hi there
Looking for a Readme on how to compile it under Linux. Not being a developer I am struggling a bit..
Any third parties soft. required apart from Matlab compiler?
Many thanks
Ed

**Comment by sjohnson-imi** [comment]
The Matlab compiler is not needed: the code is all QT / C++

You need only the QT compiler and the third party libraries listed in the .pro file: libdpx, libav, and dspfilters

**Comment by fabriziocarraro** [comment]
Compiling under macOS. Everything almost ok, but where can I find the required libraries?

# Additional libraries required:
# libav (the ffmpeg libraries)
# dpx
# dspfilters
# openexr

Any hints? Thanks a lot.
Fabrizio

**Comment by sjohnson-imi** [comment]
I usually find them via Google:

https://www.libav.org/
https://github.com/PatrickPalmer/dpx
https://github.com/vinniefalco/DSPFilters

And note that OpenEXR isn't implemented in AEO-Light yet, so this isn't yet required:

www.openexr.com/

**Comment by retokromer** [comment]
You better would use: 
https://ffmpeg.org
