### ISSUE TITLE
Linux build instructions

### ISSUE THREAD

**Issue by znerol** [usc-imi/aeo-light#20]
Regrettably the wiki is read-only, thus dumping my notes on how to build AEO-light on linux as a ticket (a participant from @retokromer Annecy workshop pestered me to finally complete that task now...). Note, instructions are written as a Dockerfile, thus it is easier to test them. Use `docker cp` in order to retrieve the binary after a successfull build. Note that in order to actually run the binary on other machines it is necessary to install the required runtime libraries (i.e., libtiff, qt5 including the multimedia component and ffmpeg). Also it is necessary to also retrieve `/usr/local/lib/libDSPFilters.so` from the image, since that one is not linked statically.

* Gist with [build instructions for centos](https://gist.github.com/znerol/3f56762feca53f6677e7b3d218734604)
* Gist with [build instructions for debian](https://gist.github.com/znerol/cdd294fc9d4c2a7a01693b22f7b7dcf5)

**Comment by retokromer** [comment]
Thank you very much indeed @znerol for this!

**Comment by wilsbacher** [comment]
Have made a quick series of edits to wiki to include these instructions. Thank you @znerol!
