### ISSUE TITLE
24 Hz Clicking Artifact with Length Modulated Sound (Possibly due to poor calibration / small overlap) 

### ISSUE THREAD

**Issue by mltschlz** [usc-imi/aeo-light#32]
Hello everyone, 

first of all, thank you so much for creating AEO-Light. It is a very impressive piece of software helping me a lot with my personal project: I am currently working on a digital restoration of the first feature film my late father directed in 1981 ("Der Tod in der Waschstraße" [www.imdb.com/title/tt0083213](http://www.imdb.com/title/tt0083213)). Luckily I could locate the original camera negatives and was able to digitize everything frame by frame at my former workplace using an ARRISCAN XT 35 mm scanner (thank you ARRI!).

Converting the first reel of the sound negative went splendidly using AEO-Light. However, unfortunately for the remaining four reels of the film we accidentally must have used a different scanner gate which ever so slightly cropped the sound negative frames just a little bit. (I didn't notice this while scanning but unfortunately only now, months later). So for example the bottom border of a frame might look like this:

![image](https://user-images.githubusercontent.com/67609487/86182928-2cf0ed80-bb31-11ea-883c-a1cecc1a6bee.png)

Now, there are three issues: 
(1) The black border creates an artificial signal (needs to be cropped) 
(2) There is a smaller overlap between consecutive frames, so the stitching algorithm could run into problems. 
(3) Due to the gate the illumination could be different close to the gate border (--> possibly needs to be fixed by calibration) 

Regarding (1) I cropped the frames myself (or more precisely I zoomed in a bit with Davinci Resolve). Regarding (2), luckily there still seems to be a little bit of overlap, but my frame settings in AEO-Light are really at its extreme values:

<img width="353" alt="Screenshot 2020-06-30 22 01 25" src="https://user-images.githubusercontent.com/67609487/86184817-33816400-bb35-11ea-81f1-26ec44332171.png">

<img width="331" alt="Screenshot 2020-06-30 22 01 29" src="https://user-images.githubusercontent.com/67609487/86184860-472cca80-bb35-11ea-8862-c86476cdbcaa.png">

Regarding issue (3) the calibration feature of AEO-Light does not seem to fix the problem (Is it more aimed at density modulated sound?). Basically, running AEO-Light, unfortunately still **creates a 24 Hz "clicking" for quiet parts of the film**. As soon as there is more signal it seems to work better (see sample extraction on shared link below). Now, I am not sure how to proceed. I also don't know if the problem comes from issue (2) or issue (3) or a combination of both. 

Does anyone have any idea what I could try to fix this? If you want to look the data, that's possible. I have uploaded 500 frames of the second act (also the "zoomed" frames from Resolve): 

[http://maltefilm.de/filerun/wl/?id=KRWVoXnIqrj6rhesKKw8WcaFLkspvPBR](http://maltefilm.de/filerun/wl/?id=KRWVoXnIqrj6rhesKKw8WcaFLkspvPBR)

By the way, the files on the server have been corrected for dust artifacts and transcoded to monochrome dpx. So it's not the original scan. Let me know, if you think it might help to have a look at the original scan. I am grateful for any piece of advice! 

Thank you so much in advance,

Malte

**Comment by Ana77777** [comment]
Try Audacity 1.2.6 noise removal. Or another program.  
[https://yadi.sk/d/ozHLHjtZZjwQNA](url)

**Comment by mltschlz** [comment]
Thank you for the idea, Ana77777! I agree that noise reduction might improve the outcome in the end, but I'd much prefer to get a cleaner signal out of the conversion. Otherwise it will be challenging to differentiate between artifacts from the conversion and intentional creative sound design from the creative process. For example, "background noise" is to some extend just the room tone used during production.

Do you or anyone see any change of improving the extraction process. To me it looks like the signal stitching of consecutive frames causes the artifact. Again, any ideas / help / hints would be greatly appreciated. :)

**Comment by wilsbacher** [comment]
The very first thing to confirm is whether or not the change in the framing of the scans resulted in the loss of a complete record of the soundtrack throughout the entire 4-perf pitch of the negative. It is quite possible that the scans for this reel do not contain all the audio information from negative. When this happens you'll get a clicking artifact. No amount of fiddling with settings can restore data not captured in the original scan. 

One way to do this: (1) set up the setting per normal; (2) under "view options" check "show overlap" (3) move the frame pitch begin and end sliders to see the overlap visual information moving.  If there is a solid block of black pixels running across the entire frame that changes width when BUT never goes away, then you are missing data and the negative will have to be rescanned.

**Comment by mltschlz** [comment]
Hi Greg, 

thanks a lot for your reply! I followed your steps. After the initial setup I do see a small overlap (yellow line in the waveform zoom). Looks something like this:

![image](https://user-images.githubusercontent.com/67609487/87045674-722fb200-c1f8-11ea-9866-9d8fc74f4fda.png)

Basically, here both the frame pitch begin and frame pitch end sliders are both set (very close) to zero. If I increase the frame pitch begin slider the upper part of the image (above the overlap indicator) will move upwards, increasing the width of the black bar. If on the other hand I increase the frame pitch end slider it will move downward and the black bar will indeed disappear (but it doesn't look like a good fit anymore).

From the screenshot above you also see that the waveform zoom shows signal drops at the outermost part of the frame. This motivated me to try and crop the frame a bit more (to get rid of the signal drops). With a bigger crop of the frames, of course, the yellow signal overlap in the waveform zoom gets even smaller:

![image](https://user-images.githubusercontent.com/67609487/87046865-fcc4e100-c1f9-11ea-9bb8-913654d80ddd.png)

Here, you also see a dotted red line in the waveform zoom. Still looks like some kind of signal drop, but I couldn't get rid of it no matter in what way I crop the images. 

In order to confirm that there is an overlap between consecutive frames, I also tried to manually stitch consecutive frames, by using two video tracks and crops in an video editing software:

![image](https://user-images.githubusercontent.com/67609487/87049246-07cd4080-c1fd-11ea-877d-4e37e2183faa.png)

(Here I added some coloring to better visualize the apparent overlap (green) and the part of the next frame (yellow))
Still, no matter what I do, there is always to some extend that 24 Hz artifact (even the manual stitch didn't improve the result).

Unfortunately, it won't be easy to do a re-scan as I currently don't have access to the required resources. Still it could be possible some day. I also made an inquiry at the German broadcasting archive to hopefully find another source for the audio (like a magnetic recording), but I don't know yet if another source exists or what quality I could get out of that.

Please let me know, what you think and if there are other things I could try with AEO-Light.

Best
Malte

**Comment by taschenbach** [comment]
Try with search region smaller. To have it auto center to a detected location use the following procedure:
- Setup AEO light the way you have been testing.
- Step forward through some frames until where the change in modulation in the overlap area(as in you picture) is unique and confirm it has detected.
- Click the lock height box. This will snap the center of the search region to current detected location.
- Since it is on an Arri Scan it is going to be steady, but you should test two different methods from here:
a. Leave lock height on - make a test sample
b. Make the search region much smaller maybe 0.01 and then turn off lock height - make a test sample

Tommy

**Comment by mltschlz** [comment]
So, great news!!! After some additional parameter tweaking and image processing I finally managed to get a very clean conversion from AEO-Light. I am very happy. In case you are interested, here is what I did:

Firstly, I followed Tommy's advice to reduce the search area and possibly switch "lock height" on. Before, I had already reduced the search area to 0.03 in order to get the two curves to overlap. However, reducing it even further with or without "lock height" on didn't change the outcome at all. There was, unfortunately, always the 24 Hz artifact.

So since this set of parameters didn't change the result at all, I thought that this was maybe the wrong place to look at. I then focused at the "edge artifact" from a difference in illumination close to the gate. In fact the audio tracks look kind of "broken" close to the edges:

![image](https://user-images.githubusercontent.com/67609487/87349353-73ddda80-c556-11ea-852f-7d388cdb0562.png)

I tried to "repair" these by adjusting the contrast curve in DaVinci Resolve and adding some sharpening.

![image](https://user-images.githubusercontent.com/67609487/87350404-18145100-c558-11ea-897b-e5d56bf22331.png)

![image](https://user-images.githubusercontent.com/67609487/87350067-a0462680-c557-11ea-89e7-92a196345c55.png)

With this image processing, the waveform zoom of AEO-Light still shows a kind of "signal drop" in the edges (what I mean are those dotted lines around the yellow part of the curve):

![image](https://user-images.githubusercontent.com/67609487/87349736-172eef80-c557-11ea-9941-b6aa46d2ff73.png)

However, the sound is really good now. I do not hear any 24 Hz artifact. So it looks like this is just the right "middle ground" for a good conversion. Thanks again to everyone for your help! I think this threat can be closed now. ;) 

All the best and thanks again!

Malte

_P.S.: In general, from working with AEO-Light I would have some ideas for improvements:_

_(1) A simple cropping feature could be nice. I had to do the cropping in Davinci Resolve and re-render sequences for the parameter tweaking._

_(2) Since my scan has a very high resolution (it's a 6K scan with about 4300 lines) it might have been beneficial to adjust the search region as well as frame pitch start/end values with a lower granularity. Currently, these values can only be changed in steps of 0.01, but for me a more precise adjustment might have helped._

**Comment by wilsbacher** [comment]
Malte, 

Very glad you were able to identify and address the issue in Resolve and get good sound from AEO-light 2 afterwards. We will close this thread but would you be willing to create a "Feature Request" ticket for suggestion #2 ?  I think this is worth us looking into. IMO the cropping feature would be out of scope for this software.
