### ISSUE TITLE
Please help! - Error extracting sound:  Could not read requested frame number: 1

### ISSUE THREAD

**Issue by IMMORTEN** [usc-imi/aeo-light#37]
Please help!

I tried watching the "how-to" video on youtube and set it up accordingly (Link to video: https://www.youtube.com/watch?v=KRG3nGpnBTA) 

But it doesn't pick up any sound at al when I try to do a sample, and when I try to extract sound I gives me an error (stated in the title) - I'l attach the error log below:

Starting project: 
Fri Feb 19 12:02:28 2021
Opening starting project
New frame window
GL Error in ../aeo-light/frame_view_gl.cpp at line 593:
Invalid Operation

GL Error in ../aeo-light/frame_view_gl.cpp at line 597:
Invalid Operation

GL Error in ../aeo-light/frame_view_gl.cpp at line 614:
Invalid Operation

GL Error in ../aeo-light/frame_view_gl.cpp at line 819:
Invalid Operation

 OpenGL overlap 0 Using OpenGL 0 FrameStart 0 FrameStop 1 start search 4 end search 4   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.1 FrameStop 1.1 start search 190 end search 290   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.1 FrameStop 1.1 start search 190 end search 290   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.1 FrameStop 1.1 start search 190 end search 290   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.1 FrameStop 1.1 start search 190 end search 290   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.1 FrameStop 1.1 start search 190 end search 290   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.108 FrameStop 1.108 start search 205 end search 306   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.108 FrameStop 1.108 start search 381 end search 482   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.108 FrameStop 1.108 start search 381 end search 482   0
Fri Feb 19 12:04:33 2021
AEO-Light v2.3.3
Source: /Volumes/G-Drive - JBOD Setup/Test af Optisk lyd/Edit version.mp4
Output: /var/folders/pg/b4722jt97gs7sndh8wvqphkm0000gn/T/aeoJL2837.wav
Size: 1920x1080

----- OpenGL SETTINGS -----
AEO-Light Project Settings
Source Scan = /Volumes/G-Drive - JBOD Setup/Test af Optisk lyd/Edit version.mp4
Source Format = LibAV Video
Frame Rate = 23.976 fps
Use Soundtrack = 1
Left Boundary = 1480
Right Boundary = 1615
Soundtrack Type = Mono
Use Pix Track = 1
Left Pix Boundary = 646
Right Pix Boundary = 1447
Frame Pitch Start = 178
Frame Pitch End = 271
Overlap Search Size = 5
Frame Translation = 200
Lift = 0
Gamma = 100
Gain = 100
S-Curve Value = 300
S-Curve On = 0
Blur = 0
Negative = 0
Desaturate = 0
Calibrate = 0
Export Frame In = 0
Export Frame Out = 6725
Export Sampling Rate = 48khz
Export Bit Depth = 16 Bit
Timecode Advance = 0
Export XML Sidecar = None
View Zoom = 0
View Overlap = 0
View Soundtrack Only = 1
View Frame = 496
---------------------------
OpenGL version 2.1
Frame window is exposed.
FileRealBuffer = [0x1213fc000,0x1214e7000] (2x240240
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
Fri Feb 19 12:05:52 2021
AEO-Light v2.3.3
Source: /Volumes/G-Drive - JBOD Setup/Test af Optisk lyd/Edit version.mp4
Output: /Volumes/G-Drive - JBOD Setup/Test af Optisk lyd/Extract test 1.wav
Size: 1920x1080

----- OpenGL SETTINGS -----
AEO-Light Project Settings
Source Scan = /Volumes/G-Drive - JBOD Setup/Test af Optisk lyd/Edit version.mp4
Source Format = LibAV Video
Frame Rate = 23.976 fps
Use Soundtrack = 1
Left Boundary = 1480
Right Boundary = 1615
Soundtrack Type = Mono
Use Pix Track = 1
Left Pix Boundary = 646
Right Pix Boundary = 1447
Frame Pitch Start = 178
Frame Pitch End = 271
Overlap Search Size = 5
Frame Translation = 200
Lift = 0
Gamma = 100
Gain = 100
S-Curve Value = 300
S-Curve On = 0
Blur = 0
Negative = 0
Desaturate = 0
Calibrate = 0
Export Frame In = 0
Export Frame Out = 6725
Export Sampling Rate = 48khz
Export Bit Depth = 16 Bit
Timecode Advance = 26
Export XML Sidecar = None
View Zoom = 0
View Overlap = 0
View Soundtrack Only = 0
View Frame = 496
---------------------------
OpenGL version 2.1
Frame window is exposed.
FileRealBuffer = [0x12783f000,0x12ab9d000] (2x13465452
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0
 OpenGL overlap 0 Using OpenGL 0 FrameStart 0.178 FrameStop 1.178 start search 847 end search 948   0

Sound extraction canceled before finishing.
Fri Feb 19 12:11:06 2021

**Comment by bbito** [comment]
I think interframe compression codecs such as the h.264/h.265 generally found in MP4 containers often cause problems. I haven't tried one in years and instead use DPX sources. See also https://github.com/usc-imi/aeo-light/issues/10 which suggests several image sequence formats are working for other users.

**Comment by IMMORTEN** [comment]
> I think interframe compression codecs such as the h.264/h.265 generally found in MP4 containers often cause problems. I haven't tried one in years and instead use DPX sources. See also #10 which suggests several image sequence formats are working for other users.

On my Mac I can't get it to pick up any sound at all...like literally none at all....and if I hit calibrate the program just crashes.

On my PC, it does pick up sound, but it will only extract 2000 frames at a time, otherwise it will give me an error saying there was 1 frame it couldn't read, and it canceled the whole sound extraction.

I tried making an image sequence in the form of DPX files, but it will only allow me to import 1 frame at a time. How do you get it to work with all of the DPX files in the image sequence?

**Comment by sjohnson-imi** [comment]
If the DPX files are named with a sequential frame number portion in the filename (e.g., mymovie00001.dpx, mymovie00002.dpx, ...), then opening one of those files will open the whole sequence.

**Comment by IMMORTEN** [comment]
Look gentlemen....and ladies....and whatever other creatures are out there.....After about 8 million attempts of trial and error, I found out that for this program to work....the files needs to be in .avi format and with an image codecs (tiff, jpeg any will work)....AND THATS IT!!

This is not mentioned in any manual / documentation or how-to videos anywhere...trust me I have looked...

I don't know what it is everyone keeps babbling on about DPX files ...frames...or what not... or why the above would have been so difficult to mention in any of the documentations..manuals...how-to videos and so on....but that is it! ---thats all you have to do!

If you make a DPX frame sequence; it will only import one frame at a time, IT WILL NOT import all the frames or the whole sequence....maybe it is supposed to...but IT DOES NOT....as in; it doesn't happen. 

So to anyone who speaks english; all you have to do, is make your video files as .avi files and choose an image codecs and import that into AEO-Light....THAT IS IT! ...then the program will work and it works surprisingly well too.

Again I really don't understand why this would have been so difficult to mention anywhere, but hopefully other people experiencing this problem will see this post and it will save them a huge headache......the ginormous it gave me trying to figure this out.. 


Alright; I think we are done here.

**Comment by wilsbacher** [comment]
Confirming that AEO-light 2 fully supports DPX as an input provided that sequential naming is adhered to. It also supports .mov and .avi wrappers. As others have noted, interframe compression codecs are not supported.
