### ISSUE TITLE
The minimum resolution for CD quality

### ISSUE THREAD

**Issue by maheelrp** [usc-imi/aeo-light#38]
What is the minimum required resolution for the scan to get CD Quality audio from the extract?

**Comment by sjohnson-imi** [comment]
If you want 44.1kHz samples, then you need 44.1 thousand horizontal lines of resolution per second of scan. If you have 24fps, then you need 44.1k / 24 = 1838 lines of resolution (plus the overscan area) in the scan.

**Comment by maheelrp** [comment]
I have read somewhere that I need twice that resolution. That is why I posted the question here. Thanks for the clarification.
