### ISSUE TITLE
Installing in Linux

### ISSUE THREAD

**Issue by acastles91** [usc-imi/aeo-light#40]
I am trying to install this project in Linux but I don't find any compilation instructions. Can someone point out to an installation guide to a Linux machine? Is the project being maintained? Thanks in advance.

**Comment by retokromer** [comment]
Have you checked the Wiki?

https://github.com/usc-imi/aeo-light/wiki/Linux-build-instructions-for-AEO-light-(with-thanks-to-@znerol)

**Comment by acastles91** [comment]
Thank you, I totally missed that.
