### ISSUE TITLE
No waveform computed (AEO-Light 2.2 beta OS X)

### ISSUE THREAD

**Issue by z-l-p** [usc-imi/aeo-light#6]
Hi. I've been using the original AEO-Light version for awhile and loving it. On my older (2011) Mac Pro it launches and the UI works without  errors, but no waveform is computed when I view frames. The logfile shows several errors:

```
New frame window
GL Error in ../aeo-light/frame_view_gl.cpp at line 589:
Invalid Operation

GL Error in ../aeo-light/frame_view_gl.cpp at line 593:
Invalid Operation

GL Error in ../aeo-light/frame_view_gl.cpp at line 610:
Invalid Operation

GL Error in ../aeo-light/frame_view_gl.cpp at line 796:
Invalid Operation
```

My GPU is a Radeon HD 5770 with 1GB VRAM. Any idea what's going on? (It works great on several modern Macs.)
-Z

**Comment by sjohnson-imi** [comment]
Those GL errors are likely inconsequential: I imagine you've got them in the log files on the other machines, too. (We get them on successful runs here as well.)

The blank waveform is probably indicative of an OpenGL version issue. You may not have OpenGL 3.0 on the older machine: check to see if an updated driver is available.

Or it could be a quirk between the AMD version of OpenGL and the Nvidia version. I believe all of our OSX tests have been on Nvidia hardware. Are your newer macs also using Radeon graphics?

We've also had reports from Windows users who upgrade their OS having GL problems as well (even though the final driver specs match those of machines that can run AEO-Light 2.x just fine). I haven't heard of such on OSX yet, but that doesn't mean it can't happen.

**Comment by z-l-p** [comment]
Thanks for the info. I've had success on a Macbook Pro 2105 (Radeon) and a 2012 Mini (Intel integrated GPU). The older towers with Radeon cards are the only failure cases. (There are no driver updates since they're rolled into OS updates by Apple.)  

I dug up this thread which mentions core v compatibility modes when initing the gl context: [http://stackoverflow.com/questions/25827895/ati-radeon-hd-5770-gpu-opengl-4-1-support](http://stackoverflow.com/questions/25827895/ati-radeon-hd-5770-gpu-opengl-4-1-support)
Might shed some light and I'm happy to test any fixes, but I also understand if you'd rather not spend time on older GPUs!
-Zach

**Comment by sjohnson-imi** [comment]
Interesting. I'll see if QT has equivalent calls to request higher GL versioning.

What OpenGL version is reported in the AEO log file after a failed extraction?

**Comment by z-l-p** [comment]
Away from that machine until Wednesday but will check and get back to
you.

**Comment by z-l-p** [comment]
The plot thickens: Just checked the logs. It's reporting OpenGL 2.1 on my Radeon machine (no waveform) but my Intel 4000 machine also reports 2.1 and AEO works perfectly. So GL version might be a red herring? (There are no "Invalid Operation" errors on the working machine though.)

Version 2.1 is apparently what would be reported if the hardware was addressed using Apple's legacy profile. (It should report 4.1 on either GPU using the current "Core" profile.) It's all a bit over my head but these Apple docs might help:

"Understanding and Detecting OpenGL Functionality"
 https://developer.apple.com/library/content/technotes/tn2080/_index.html

This table lists the GL capabilities of different Mac hardware using the modern "Core" profile. (Click "Legacy" to see the old capabilities.)
https://developer.apple.com/opengl/capabilities/

**Comment by retokromer** [comment]
Is this still an issue in the current version 2.3.2?

**Comment by sjohnson-imi** [comment]
AEO-Light uses some OpenGL 3.0 calls, so these must be supported by the graphics driver.
