### ISSUE TITLE
source not compiling /w gcc 4.8.5

### ISSUE THREAD

**Issue by K0F** [usc-imi/aeo-light#8]
GCC compiler (4.8.5) throws an error:

mainwindow.cpp:93:27: error: taking address of temporary array
that line in source is:
```#define aeo_av_err2str(n) av_err2str(n)```

is there any workaround, I have tried defining ```-std=c++11``` and removing ```#define``` with no luck so far

Thanks for any advice

**Comment by K0F** [comment]
Ok, adding:

```
#undef av_err2str
#define av_err2str(errnum) av_make_error_string((char*)__builtin_alloca(AV_ERROR_MAX_STRING_SIZE),AV_ERROR_MAX_STRING_SIZE, errnum)
```

Should fix the compiler error

**Comment by sjohnson-imi** [comment]
Thanks. I've added this change to 2.3.2
